### PR TITLE
Settings renamed

### LINKED ISSUE #37: Missing Doxyfile Configuration for "Service" Folder
The current configuration of the Doxyfiles doesn't include the "Service" folder, leading to incomplete documentation and undetected documentation errors.
- [x] Add the Service folder as an input in a Doxyfile.
- [ ] Fix the faulty Doxygen documentation in the Service folder.

### LINKED ISSUE #38: Settings not found
Settings.h in Servicese clashes with file included in USB host library. File and class must be renamed.

Log:
```
lib/RemoteControl/src/App.cpp: In member function 'void App::setup()':
lib/RemoteControl/src/App.cpp:101:5: error: 'Settings' was not declared in this scope
     Settings& settings     = Settings::getInstance();
     ^~~~~~~~
lib/RemoteControl/src/App.cpp:101:5: note: suggested alternative: 'SPISettings'
     Settings& settings     = Settings::getInstance();
     ^~~~~~~~
     SPISettings
lib/RemoteControl/src/App.cpp:101:15: error: 'settings' was not declared in this scope
     Settings& settings     = Settings::getInstance();
               ^~~~~~~~
lib/RemoteControl/src/App.cpp:101:15: note: suggested alternative: 'sbttons'
     Settings& settings     = Settings::getInstance();
               ^~~~~~~~
               sbttons
lib/RemoteControl/src/App.cpp:101:30: error: 'Settings' is not a class, namespace, or enumeration
     Settings& settings     = Settings::getInstance();
                              ^~~~~~~~
*** [.pio\build\RemoteControlTarget\lib0a8\RemoteControl\App.cpp.o] Error 1
```

### PR DESCRIPTION
**Pull request by gabryelreyes**
Renamed "Settings" into "SeetingsHandler" to prevent collision with libraries.
Fixed missing input files in Doxyfiles
Fixed Doxygen findings
Closes #37 
Closes #38

### CODE REVIEW

File: lib/Utilities/src/LogSinkPrinter.h [hunk 1]
```diff
@@ -150,13 +150,14 @@ class LogSinkPrinter : public LogSink
...
-    LogSinkPrinter& operator=(const LogSinkPrinter& sink);
+    /* Not allowed. */
+    LogSinkPrinter(const LogSinkPrinter& sink);            /**< Copy construction of an instance. */
+    LogSinkPrinter& operator=(const LogSinkPrinter& sink); /**< Assignment of an instance. */
 
     /**
      * Get a string representation of the given logLevel.
      *
-     * @param[in] logLevel The logLevel.
+     * @param[in] LogLevel The logLevel.
```
Comment (BlueAndi) [inline lib/Utilities/src/LogSinkPrinter.h:160]: Please fix the parameter name, it should start lowercase.

**Review by BlueAndi — CHANGES_REQUESTED** [review]

**Review by BlueAndi — APPROVED** [review]
